In [1]:
import pandas as pd
dataset=pd.read_csv("SMSSpamCollection",sep="\t",names=["labels","message"])

In [2]:
dataset

labels                                            message
0       ham  Go until jurong point, crazy.. Available only ...
1       ham                      Ok lar... Joking wif u oni...
2      spam  Free entry in 2 a wkly comp to win FA Cup fina...
3       ham  U dun say so early hor... U c already then say...
4       ham  Nah I don't think he goes to usf, he lives aro...
...     ...                                                ...
5567   spam  This is the 2nd time we have tried 2 contact u...
5568    ham               Will ü b going to esplanade fr home?
5569    ham  Pity, * was in mood for that. So...any other s...
5570    ham  The guy did some bitching but I acted like i'd...
5571    ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [3]:
dataset.isna().sum()

labels     0
message    0
dtype: int64

In [4]:
import nltk
import re
nltk.download("stopwords")

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\hp\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [5]:
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
ps=PorterStemmer()

In [8]:
corpus=[]
for i in range(0,len(dataset)):
    msg=re.sub("[^a-zA-Z]"," ",dataset["message"][i])
    msg=msg.lower()
    msg=msg.split()
    msg=[ps.stem(word) for word in msg if not word in stopwords.words('english')]
    msg=' '.join(msg)
    corpus.append(msg)

In [11]:
corpus[4]

'nah think goe usf live around though'

In [14]:
# creating bag of word model
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=2500)
X=cv.fit_transform(corpus).toarray()

In [32]:
len(X[0])

2500

In [15]:
X

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [17]:
y=pd.get_dummies(dataset["labels"])


In [19]:
y=y.iloc[:,1].values

In [20]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=0)

In [22]:
from sklearn.naive_bayes import MultinomialNB
spammodel=MultinomialNB()
spammodel.fit(X_train,y_train)

MultinomialNB()

In [23]:
y_pred=spammodel.predict(X_test)

In [24]:
from sklearn.metrics import accuracy_score,classification_report

In [25]:
score=accuracy_score(y_test,y_pred)

In [26]:
score

0.9850478468899522

In [28]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.99      0.99      0.99      1451
           1       0.94      0.95      0.94       221

    accuracy                           0.99      1672
   macro avg       0.96      0.97      0.97      1672
weighted avg       0.99      0.99      0.99      1672



In [29]:
# creating tf-idf model

In [30]:
from sklearn.feature_extraction.text import TfidfVectorizer
tv=TfidfVectorizer(max_features=2500)
X=tv.fit_transform(corpus).toarray()

In [36]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=0)


In [37]:
X

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [39]:
type(X[0][0])

numpy.float64

In [40]:
## word2vec implementation

In [41]:
!pip install gensim

     ---------------------------------------- 67.1/67.1 kB 1.8 MB/s eta 0:00:00
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
  Created wheel for fst-pso: filename=fst_pso-1.8.1-py3-none-any.whl size=20448 sha256=570f41d0df4d8aa7487ae24cabaea416173d07c03649d1389f2e840f2d0ef032
  Stored in directory: c:\users\hp\appdata\local\pip\cache\wheels\01\02\ee\df0699282986903a384b69aab4413af9efd26b3612b5dccc9e
  Created wheel for miniful: filename=miniful-0.0.6-py3-none-any.whl size=3522 sha256=c28676024491421027d0e1eb8a37f87f222ef68fe54fadba9e6e306647149595
  Stored in directory: c:\users\hp\appdata\local\pip\cache\wheels\43\aa\48\5c66b931ff013ad19774081aa19656637af5c0cc33b5494b30
Successfully built fst-pso miniful


In [42]:
import gensim.downloader as api
wv=api.load('word2vec-google-news-300')

[==================================================] 100.0% 1662.8/1662.8MB downloaded


In [48]:
wv['kite']

array([-0.07324219,  0.0456543 , -0.06738281, -0.10546875, -0.12011719,
       -0.06542969,  0.19042969,  0.08740234, -0.02514648,  0.00872803,
        0.17480469, -0.26367188, -0.29882812, -0.03710938, -0.1640625 ,
        0.29101562, -0.13085938, -0.09228516, -0.07519531, -0.11035156,
        0.03710938,  0.32421875,  0.00494385,  0.125     , -0.11376953,
       -0.10791016,  0.03271484,  0.21386719,  0.31640625, -0.27539062,
       -0.08300781, -0.13769531, -0.10253906,  0.01623535,  0.1875    ,
       -0.09179688,  0.00717163,  0.15917969,  0.07519531,  0.10009766,
        0.14355469,  0.02319336,  0.27929688,  0.06079102,  0.08935547,
       -0.12695312,  0.04663086, -0.08300781,  0.34960938, -0.12890625,
       -0.12988281,  0.0859375 ,  0.296875  , -0.07177734,  0.10644531,
       -0.16992188,  0.39453125, -0.21875   ,  0.03686523, -0.08837891,
        0.17675781, -0.34375   , -0.09619141, -0.09375   , -0.203125  ,
       -0.109375  , -0.23046875, -0.0300293 , -0.13671875,  0.13

In [58]:
from nltk.stem import WordNetLemmatizer
lemmatizer=WordNetLemmatizer()
import nltk
nltk.download('wordnet')
nltk.download('omw-1.4')


[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\hp\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to
[nltk_data]     C:\Users\hp\AppData\Roaming\nltk_data...


True

In [59]:
corpus = []
for i in range(0, len(dataset)):
    review = re.sub('[^a-zA-Z]', ' ', dataset['message'][i])
    review = review.lower()
    review = review.split()
    
    review = [lemmatizer.lemmatize(word) for word in review if not word in stopwords.words('english')]
    review = ' '.join(review)
    corpus.append(review)

In [67]:
lemmatizer.lemmatize("creeping")

'creeping'

In [73]:
from nltk import sent_tokenize
from gensim.utils import simple_preprocess
import nltk
nltk.download('punkt')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\hp\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping tokenizers\punkt.zip.


True

In [74]:
words=[]
for sent in corpus:
    sent_token=sent_tokenize(sent)
    for sent in sent_token:
        words.append(simple_preprocess(sent))

In [75]:
words

[['go',
  'jurong',
  'point',
  'crazy',
  'available',
  'bugis',
  'great',
  'world',
  'la',
  'buffet',
  'cine',
  'got',
  'amore',
  'wat'],
 ['ok', 'lar', 'joking', 'wif', 'oni'],
 ['free',
  'entry',
  'wkly',
  'comp',
  'win',
  'fa',
  'cup',
  'final',
  'tkts',
  'st',
  'may',
  'text',
  'fa',
  'receive',
  'entry',
  'question',
  'std',
  'txt',
  'rate',
  'apply'],
 ['dun', 'say', 'early', 'hor', 'already', 'say'],
 ['nah', 'think', 'go', 'usf', 'life', 'around', 'though'],
 ['freemsg',
  'hey',
  'darling',
  'week',
  'word',
  'back',
  'like',
  'fun',
  'still',
  'tb',
  'ok',
  'xxx',
  'std',
  'chgs',
  'send',
  'rcv'],
 ['even', 'brother', 'like', 'speak', 'treat', 'like', 'aid', 'patent'],
 ['per',
  'request',
  'melle',
  'melle',
  'oru',
  'minnaminunginte',
  'nurungu',
  'vettam',
  'set',
  'callertune',
  'caller',
  'press',
  'copy',
  'friend',
  'callertune'],
 ['winner',
  'valued',
  'network',
  'customer',
  'selected',
  'receivea',
 

In [76]:
import gensim

In [77]:
# training word2vec from scratch
model=gensim.models.Word2Vec(words,window=5,min_count=2)

In [78]:
model.wv.index_to_key

['call',
 'get',
 'ur',
 'gt',
 'lt',
 'go',
 'ok',
 'day',
 'free',
 'know',
 'come',
 'like',
 'time',
 'good',
 'got',
 'love',
 'text',
 'want',
 'send',
 'need',
 'one',
 'txt',
 'today',
 'going',
 'stop',
 'home',
 'lor',
 'sorry',
 'see',
 'still',
 'mobile',
 'take',
 'back',
 'da',
 'reply',
 'dont',
 'think',
 'tell',
 'week',
 'hi',
 'phone',
 'new',
 'later',
 'please',
 'pls',
 'co',
 'msg',
 'min',
 'make',
 'night',
 'dear',
 'message',
 'well',
 'say',
 'thing',
 'much',
 'oh',
 'hope',
 'claim',
 'great',
 'hey',
 'give',
 'number',
 'happy',
 'wat',
 'friend',
 'work',
 'way',
 'yes',
 'www',
 'prize',
 'let',
 'right',
 'tomorrow',
 'already',
 'tone',
 'ask',
 'win',
 'said',
 'life',
 'cash',
 'amp',
 'yeah',
 'im',
 'really',
 'meet',
 'babe',
 'find',
 'miss',
 'morning',
 'thanks',
 'last',
 'uk',
 'service',
 'year',
 'anything',
 'care',
 'would',
 'com',
 'also',
 'lol',
 'nokia',
 'feel',
 'every',
 'keep',
 'sure',
 'pick',
 'urgent',
 'sent',
 'contact',


In [79]:
model.wv.similar_by_word("kid")

[('work', 0.997779905796051),
 ('much', 0.9977782368659973),
 ('money', 0.9976816177368164),
 ('going', 0.9976251721382141),
 ('really', 0.9976064562797546),
 ('went', 0.997605562210083),
 ('would', 0.9976038932800293),
 ('like', 0.9976028800010681),
 ('sent', 0.9975953698158264),
 ('said', 0.9975880980491638)]